baseurl = ""
languageCode = "en-us"
theme = "hello-friend-ng"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "Homepage and blog by Sidd"
  keywords = "homepage, blog, science, informatics, development, programming"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # Default theme "light" or "dark"
  defaultTheme = "light"

[languages]
  [languages.en]
    title = "Call me Sidd"
    subtitle = "Just another techie"
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "$ cd /home/"
      logoHomeLink = "/"
      logoColor    = "#00cc00"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "blog"
    url        = "/posts/"
    weight     = "100"

    [[menu.main]]
    identifier = "about"
    name       = "about"
    url        = "/about/"
    weight     = "95"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/"

  [[params.social]]
    name = "email"
    url  = "mailto:siddharth28m@live.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/"

  [[params.social]]
    name = "stackoverflow"
    url  = "https://www.stackoverflow.com/"