backend:
  name: git-gateway
  branch: master

media_folder: "static/uploads"
public_folder: "uploads"

collections:
  - name: "posts"
    lable: "posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {lable: "Title", name: "title", widget: "string"}
      - {lable: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}